# Generated by Django 6.0.2 on 2026-04-27 20:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_alter_plan_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='purchased_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
