# Generated by Django 6.0.2 on 2026-03-19 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0008_badge_alter_category_options'),
        ('shoppingbag', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingbagitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='shoppingbagitem',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='shoppingbagitem',
            name='product_variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='merchandise.productvariant'),
        ),
    ]
