# Generated by Django 6.0.2 on 2026-03-19 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingbag', '0002_remove_shoppingbagitem_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingBagItem',
        ),
    ]
