# Generated by Django 3.2.25 on 2026-03-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0002_auto_20260304_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_src',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
