# Generated by Django 3.2.25 on 2026-03-04 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0003_alter_product_image_src'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='variant_title',
            new_name='stripe_product_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='inventory_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.AddField(
            model_name='product',
            name='handle',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_src',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_title', models.CharField(blank=True, max_length=255)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=80)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('inventory_quantity', models.IntegerField(default=0)),
                ('image_src', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stripe_price_id', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='merchandise.product')),
            ],
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('sku',), name='uniq_variant_sku'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'variant_title'), name='uniq_variant_per_product_title'),
        ),
    ]
