# Generated by Django 6.0.2 on 2026-04-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0003_alter_productvariant_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_src',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
