# Generated by Django 6.0.2 on 2026-03-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0004_auto_20260304_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True),
        ),
    ]
