# Generated by Django 6.0.2 on 2026-03-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0005_alter_productvariant_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
            ],
        ),
    ]
