# Generated by Django 6.0.2 on 2026-03-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0008_badge_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
