# Generated by Django 6.0.2 on 2026-03-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussionboard', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vote_total',
            field=models.IntegerField(default=0),
        ),
    ]
